<?php

declare(strict_types=1);

namespace Vortos\Observability\Dashboard;

/**
 * Renders {@see DashboardSection}s into an importable Grafana dashboard document.
 *
 * Emits schemaVersion 39 (Grafana 10/11), which is what Grafana Cloud imports today. Panels are
 * laid out two per row at half width; Grafana reflows them on import, so the geometry only has to
 * be valid, not beautiful.
 */
final class GrafanaDashboardBuilder
{
    private const PANEL_WIDTH = 12;
    private const PANEL_HEIGHT = 8;
    private const ROW_HEIGHT = 1;

    public function __construct(
        private readonly FrameworkDashboardCatalog $catalog = new FrameworkDashboardCatalog(),
    ) {}

    /**
     * @return array<string, mixed> the dashboard document, ready for json_encode
     */
    public function build(string $title, string $datasourceUid, string $uid): array
    {
        $panels = [];
        $panelId = 1;
        $y = 0;

        foreach ($this->catalog->sections() as $section) {
            $panels[] = [
                'type'      => 'row',
                'title'     => $section->title,
                'collapsed' => false,
                'id'        => $panelId++,
                'gridPos'   => ['h' => self::ROW_HEIGHT, 'w' => 24, 'x' => 0, 'y' => $y],
            ];
            $y += self::ROW_HEIGHT;

            $x = 0;

            foreach ($section->panels as $panel) {
                $panels[] = $this->renderPanel($panel, $panelId++, $datasourceUid, $x, $y);

                $x += self::PANEL_WIDTH;

                if ($x >= 24) {
                    $x = 0;
                    $y += self::PANEL_HEIGHT;
                }
            }

            if ($x !== 0) {
                $y += self::PANEL_HEIGHT;
            }
        }

        return [
            'uid'           => $uid,
            'title'         => $title,
            'schemaVersion' => 39,
            'version'       => 1,
            'editable'      => true,
            'refresh'       => '1m',
            'time'          => ['from' => 'now-6h', 'to' => 'now'],
            'tags'          => ['vortos', 'generated'],
            // Marks the document as machine-generated so a reviewer knows edits belong in
            // FrameworkDashboardCatalog, not in the Grafana UI where they would be overwritten.
            'description'   => 'Generated by vortos:observability:dashboard. Edit FrameworkDashboardCatalog and regenerate; UI edits are lost on the next import.',
            'panels'        => $panels,
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function renderPanel(DashboardPanel $panel, int $id, string $datasourceUid, int $x, int $y): array
    {
        $steps = [['color' => 'green', 'value' => null]];

        if ($panel->warnThreshold !== null) {
            $steps[] = ['color' => 'yellow', 'value' => $panel->warnThreshold];
        }

        if ($panel->criticalThreshold !== null) {
            $steps[] = ['color' => 'red', 'value' => $panel->criticalThreshold];
        }

        return [
            'id'          => $id,
            'type'        => $panel->type->value,
            'title'       => $panel->title,
            'description' => $panel->description,
            'datasource'  => ['type' => 'prometheus', 'uid' => $datasourceUid],
            'gridPos'     => ['h' => self::PANEL_HEIGHT, 'w' => self::PANEL_WIDTH, 'x' => $x, 'y' => $y],
            'fieldConfig' => [
                'defaults' => [
                    'unit'       => $panel->unit,
                    'thresholds' => ['mode' => 'absolute', 'steps' => $steps],
                ],
                'overrides' => [],
            ],
            'targets' => [[
                'refId'        => 'A',
                'expr'         => $panel->query,
                'legendFormat' => $panel->legend !== '' ? $panel->legend : '__auto',
                'datasource'   => ['type' => 'prometheus', 'uid' => $datasourceUid],
            ]],
        ];
    }
}
